name: Create release

on:
  workflow_dispatch:

env:
  POETRY_VERSION: "1.2.1"

jobs:
  create-release:
    name: Create a new release
    runs-on: ubuntu-latest
    concurrency: create-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # NOTE: this is required for the python semantic release to work
      with:
        fetch-depth: 0

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}

    - name: Install dependencies required
      run: |
        poetry install --only dev

    - name: Build package
      run: |
        poetry run semantic-release version
        make dist

    - name: Finish release procedure
      run: |
        poetry run semantic-release publish --retry

    # - name: Python semantic release
    #   uses: relekang/python-semantic-release@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
        # repository_username: ${{ secrets.PYPI_USERNAME }}
        # repository_password: ${{ secrets.PYPI_TOKEN }}

    - name: Upload package to PyPI
      run: |
        # make publish
        echo "Publishing with Poetry"
